function [outputPath, label, source] = NewEpochGroup()
    handles.outputPath = '';
    handles.label = '';
    handles.source = '';
    
    handles.figure = dialog(...
        'Units', 'points', ...
        'Name', 'New Epoch Group', ...
        'Position', centerWindowOnScreen(350, 150), ...
        'Tag', 'figure');

    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'right', ...
        'Position', [10 110 100 18], ...
        'String',  'Output path:',...
        'Style', 'text');
    handles.outputPathEdit = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'left', ...
        'Position', [115 110 225 26], ...
        'String',  '',...
        'Style', 'edit', ...
        'Tag', 'outputPathEdit');
    
    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'right', ...
        'Position', [10 80 100 18], ...
        'String',  'Label:',...
        'Style', 'text');
    handles.labelEdit = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'left', ...
        'Position', [115 80 225 26], ...
        'String',  '',...
        'Style', 'edit', ...
        'Tag', 'labelEdit');
    
    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'right', ...
        'Position', [10 50 100 18], ...
        'String',  'Source:',...
        'Style', 'text');
    handles.sourceEdit = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'left', ...
        'Position', [115 50 225 26], ...
        'String',  '',...
        'Style', 'edit', ...
        'Tag', 'sourceEdit');
    
    handles.cancelButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)cancelNewGroup(hObject,eventdata,guidata(hObject)), ...
        'Position', [10 10 56 20], ...
        'String', 'Cancel', ...
        'Tag', 'cancelButton');
    
    handles.saveButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)saveNewGroup(hObject,eventdata,guidata(hObject)), ...
        'Position', [80 10 56 20], ...
        'String', 'Save', ...
        'Tag', 'saveButton');
    
    guidata(handles.figure, handles);
    
    uiwait
    
    handles = guidata(handles.figure);
    outputPath = handles.outputPath;
    label = handles.label;
    source = handles.source;
    
    close(handles.figure);
end


function cancelNewGroup(~, ~, ~)
    uiresume
end


function saveNewGroup(~, ~, handles)
    handles.outputPath = get(handles.outputPathEdit, 'String');
    handles.label = get(handles.labelEdit, 'String');
    handles.source = get(handles.sourceEdit, 'String');
    guidata(handles.figure, handles);
    
    % Remember these parameters for the next time the protocol is used.
    %setpref('ProtocolDefaults', class(handles.pluginInstance), handles.pluginInstance.parameters());
    
    uiresume
end
