function [label, parent] = newSource()
    handles.label = '';
    handles.parent = '';
    
    handles.figure = dialog(...
        'Units', 'points', ...
        'Name', 'New Source', ...
        'Position', centerWindowOnScreen(350, 120), ...
        'WindowKeyPressFcn', @(hObject, eventdata)keyPressCallback(hObject, eventdata, guidata(hObject)), ...
        'Tag', 'figure');
    
    % Label controls
    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'right', ...
        'Position', [10 80 100 18], ...
        'String',  'Label:',...
        'Style', 'text');
    handles.labelEdit = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'left', ...
        'Position', [115 80 225 26], ...
        'String',  '',...
        'Style', 'edit', ...
        'Tag', 'labelEdit');
    
    % Source controls
    uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'right', ...
        'Position', [10 50 100 18], ...
        'String',  'Parent:',...
        'Style', 'text');
    handles.parentPopup = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'FontSize', 12,...
        'HorizontalAlignment', 'left', ...
        'Position', [115 45 175 26], ...
        'String',  'None',...
        'Style', 'popupmenu', ...
        'Tag', 'parentPopup');
    handles.newSourceButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)createNewParent(hObject,eventdata,guidata(hObject)), ...
        'Position', [287 52 50 22], ...
        'String', 'New...', ...
        'Tag', 'newParentButton');
    updateParentsPopup(handles);
    
    handles.cancelButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)cancelNewSource(hObject,eventdata,guidata(hObject)), ...
        'Position', [10 10 56 20], ...
        'String', 'Cancel', ...
        'Tag', 'cancelButton');
    
    handles.saveButton = uicontrol(...
        'Parent', handles.figure,...
        'Units', 'points', ...
        'Callback', @(hObject,eventdata)saveNewSource(hObject,eventdata,guidata(hObject)), ...
        'Position', [80 10 56 20], ...
        'String', 'Save', ...
        'Tag', 'saveButton');
    
    guidata(handles.figure, handles);
    
    uiwait;
    
    handles = guidata(handles.figure);
    label = handles.label;
    parent = handles.parent;
    
    close(handles.figure);
end


function updateParentsPopup(handles, sourceToSelect)
    if nargin == 1
        sourceToSelect = 'None';
    end
    sources = struct('label', 'None', 'parent', '');
    if ispref('Symphony', 'Sources')
        savedSources = getpref('Symphony', 'Sources');
        sources = horzcat(sources, savedSources);
    end
    labels = sort({sources.label});
    set(handles.parentPopup, 'String', labels);
    value = find(strcmp(labels, sourceToSelect));
    if isempty(value)
        errordlg(['There is no source with the label ''' sourceToSelect ''''], 'Symphony');
        value = 1;
    end
    set(handles.parentPopup, 'Value', value);
end


function keyPressCallback(hObject, eventdata, handles)
    if strcmp(eventdata.Key, 'return')
        % Move focus off of any edit text so the changes can be seen.
        uicontrol(handles.saveButton);
        
        saveNewSource(hObject, eventdata, handles);
    elseif strcmp(eventdata.Key, 'escape')
        cancelNewSource(hObject, eventdata, handles);
    end
end


function createNewParent(~, ~, handles)
    [label, ~] = newSource();
    if ~isempty(label)
        updateParentsPopup(handles, label);
    end
end


function cancelNewSource(~, ~, ~)
    uiresume;
end


function saveNewSource(~, ~, handles)
    % TODO: validate inputs
    
    handles.label = get(handles.labelEdit, 'String');
    parentLabels = get(handles.parentPopup, 'String');
    handles.parent = parentLabels{get(handles.parentPopup, 'Value')};
    if strcmp(handles.parent, 'None')
        handles.parent = '';
    end
    guidata(handles.figure, handles);
    
    % Remember these parameters for the next time the protocol is used.
    newSource.label = handles.label;
    newSource.parent = handles.parent;
    if ispref('Symphony', 'Sources')
        sources = getpref('Symphony', 'Sources');
        if strcmp('None', newSource.label) || any(strcmp({sources.label}, newSource.label))
            errordlg('A source with that label already exists.', 'Symphony');
            return
        end
        sources(end + 1) = newSource;
    else
        sources = newSource;
    end
    setpref('Symphony', 'Sources', sources);
    
    uiresume;
end
